# Generated by Django 4.1.7 on 2023-03-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_registration_nderuh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(),
        ),
    ]
